# Generated by Django 5.1.3 on 2024-11-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
