# Generated by Django 5.1.3 on 2024-11-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0003_profile_is_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_courses', to='users.profile'),
        ),
    ]
